<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZcB0ipn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZcB0ipn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZcB0ipn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZcB0ipn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZcB0ipn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZcB0ipn',
    'container.build_id' => '30bc923a',
    'container.build_time' => 1588009404,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZcB0ipn');
