<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'add_customer' => [[], ['_controller' => 'App\\Controller\\CustomerController::addCustomer'], [], [['text', '/customer/add']], [], []],
    'get_one_customer' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::getOneCustomer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/customer/get']], [], []],
    'get_all_customers' => [[], ['_controller' => 'App\\Controller\\CustomerController::getAllCustomers'], [], [['text', '/customer/get-all']], [], []],
    'update_customer' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::updateCustomer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/customer/update']], [], []],
    'delete_customer' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::deleteCustomer'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/customer/delete']], [], []],
    'consumer' => [[], ['_controller' => 'App\\Controller\\CustomerController::consumer'], [], [['text', '/customer/consumer']], [], []],
];
